# Config file for automatic testing at travis-ci.org

language: python

python:
  - "{{ cookiecutter.python_version.split('.')[:2] | join('.') }}"

before_install:
    - pip install -r requirements-dev.txt

install:
    - python setup.py install
    - pip install coveralls --use-wheel

script:
    - py.test -v --flake8 --cov-config .coveragerc --cov {{ cookiecutter.pkg_name }}

after_success:
    - coveralls
